// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: W10M

#include "ui.h"
#include "ui_helpers.h"
#include "ui_common.h"
#include "stars.h"

///////////////////// VARIABLES ////////////////////
void closeNotificationPanel_Animation(lv_obj_t *TargetObject, int delay);
void openNotificationPanel_Animation(lv_obj_t *TargetObject, int delay);
void liveTileVertical6_Animation(lv_obj_t *TargetObject, int delay);
void liveTileHorizontal5_Animation(lv_obj_t *TargetObject, int delay);
void cortanaPulse_Animation(lv_obj_t *TargetObject, int delay);
void closePanelDown_Animation(lv_obj_t *TargetObject, int delay);
void openPanelUp_Animation(lv_obj_t *TargetObject, int delay);

// SCREEN: ui_homeScreen
void ui_homeScreen_screen_init(void);
lv_obj_t *ui_homeScreen;
lv_obj_t *ui_homePanel;
lv_obj_t *ui_startPanel;
lv_obj_t *ui_Panel7;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Panel13;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_Label8;
void ui_event_Panel6(lv_event_t *e);
lv_obj_t *ui_Panel6;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Panel8;
lv_obj_t *ui_Label10;
void ui_event_Panel12(lv_event_t *e);
lv_obj_t *ui_Panel12;
lv_obj_t *ui_Label14;
lv_obj_t *ui_tipsLiveImage;
void ui_event_Panel11(lv_event_t *e);
lv_obj_t *ui_Panel11;
lv_obj_t *ui_Label13;
lv_obj_t *ui_newsLiveImage;
lv_obj_t *ui_Panel14;
lv_obj_t *ui_Label16;
lv_obj_t *ui_Panel10;
lv_obj_t *ui_Label12;
lv_obj_t *ui_photosLiveImage;
lv_obj_t *ui_Panel9;
lv_obj_t *ui_Label11;
void ui_event_Panel15(lv_event_t *e);
lv_obj_t *ui_Panel15;
lv_obj_t *ui_Label17;
lv_obj_t *ui_Panel16;
lv_obj_t *ui_Label18;
lv_obj_t *ui_allAppsPanel;
lv_obj_t *ui_allAppsLabel;
lv_obj_t *ui_allAppsIcon;
lv_obj_t *ui_appsListPanel;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Panel18;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Panel19;
lv_obj_t *ui_Panel20;
lv_obj_t *ui_Label20;
void ui_event_cortanaPanel(lv_event_t *e);
lv_obj_t *ui_cortanaPanel;
lv_obj_t *ui_TextArea3;
lv_obj_t *ui_Label6;
lv_obj_t *ui_cortanaIcon;
lv_obj_t *ui_navPanel;
lv_obj_t *ui_navBack;
lv_obj_t *ui_navHome;
lv_obj_t *ui_navSearch;
void ui_event_lockScreenPanel(lv_event_t *e);
lv_obj_t *ui_lockScreenPanel;
lv_obj_t *ui_Label41;
lv_obj_t *ui_Label39;
void ui_event_notificationPanel(lv_event_t *e);
lv_obj_t *ui_notificationPanel;
lv_obj_t *ui_quickActionPanel;
lv_obj_t *ui_Button4;
lv_obj_t *ui_Image4;
lv_obj_t *ui_Label30;
lv_obj_t *ui_Button5;
lv_obj_t *ui_Image5;
lv_obj_t *ui_Label31;
lv_obj_t *ui_Button6;
lv_obj_t *ui_Image6;
lv_obj_t *ui_Label32;
lv_obj_t *ui_Button7;
lv_obj_t *ui_Image7;
lv_obj_t *ui_Label33;
lv_obj_t *ui_Button8;
lv_obj_t *ui_Image8;
lv_obj_t *ui_Label34;
lv_obj_t *ui_Button2;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Label24;
lv_obj_t *ui_Button3;
lv_obj_t *ui_Image3;
lv_obj_t *ui_Label29;
lv_obj_t *ui_Button9;
lv_obj_t *ui_Image9;
lv_obj_t *ui_Label35;
lv_obj_t *ui_Button10;
lv_obj_t *ui_Image10;
lv_obj_t *ui_Label36;
lv_obj_t *ui_Button11;
lv_obj_t *ui_Image11;
lv_obj_t *ui_Label37;
lv_obj_t *ui_Panel30;
lv_obj_t *ui_Label38;
lv_obj_t *ui_statusPanel;
lv_obj_t *ui_statusPanelLeft;
lv_obj_t *ui_statusCellularBar;
lv_obj_t *ui_statusPanelWifi;
lv_obj_t *ui_statusPanelBluetooth;
void ui_event_statusPanelRight(lv_event_t *e);
lv_obj_t *ui_statusPanelRight;
lv_obj_t *ui_statusPanelBattery;
lv_obj_t *ui_statusPanelTime;
lv_obj_t *ui_alertPanel;
lv_obj_t *ui_alertDialogPanel;
lv_obj_t *ui_alertTitle;
lv_obj_t *ui_alertText;
void ui_event_alertbutton(lv_event_t *e);
lv_obj_t *ui_alertbutton;
lv_obj_t *ui_alertbuttonText;

// SCREEN: ui_settingsScreen
void ui_settingsScreen_screen_init(void);
lv_obj_t *ui_settingsScreen;
lv_obj_t *ui_appTitlePanel2;
lv_obj_t *ui_appTitleName2;
void ui_event_appTitleIcon2(lv_event_t *e);
lv_obj_t *ui_appTitleIcon2;
lv_obj_t *ui_settingsMainPanel;
lv_obj_t *ui_TextArea1;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Label4;

lv_obj_t *ui_settingsTitlePanel;
lv_obj_t *ui_settingsBack;
lv_obj_t *ui_settingsAppIcon;
lv_obj_t *ui_settingsAppTitle;
lv_obj_t *ui_personalizationPanel;
lv_obj_t *ui_systemPanel;
lv_obj_t *ui_themePanel;
lv_obj_t *ui_backgroundSelect;
lv_obj_t *ui_lockscreenSelect;

// SCREEN: ui_starsScreen
void ui_starsScreen_screen_init(void);
lv_obj_t *ui_starsScreen;
lv_obj_t *ui_starsTitlePanel;
lv_obj_t *ui_starsTitleName;
// void ui_event_starsTitleIcon(lv_event_t * e);
lv_obj_t *ui_starsTitleIcon;
lv_obj_t *ui_starsMainPanel;
lv_obj_t *ui_stargazersPanel;
lv_obj_t *ui_starsInfo;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Panel28;
lv_obj_t *ui_userPanel;
lv_obj_t *ui_userAvatar;
lv_obj_t *ui_userName;
lv_obj_t *ui_fullName;

// SCREEN: ui_appScreen
void ui_appScreen_screen_init(void);
lv_obj_t *ui_appScreen;
lv_obj_t *ui_appTitlePanel;
lv_obj_t *ui_appTitleName;
void ui_event_appTitleIcon(lv_event_t *e);
lv_obj_t *ui_appTitleIcon;
lv_obj_t *ui_appMainPanel;
lv_obj_t *ui_Label23;
lv_obj_t *ui_genSwitchPanel;
void ui_event_genSwitch(lv_event_t *e);
lv_obj_t *ui_genSwitch;
lv_obj_t *ui_genSwitchText;
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label25;
lv_obj_t *ui_Dropdown1;
lv_obj_t *ui_Label27;
lv_obj_t *ui_Slider1;
lv_obj_t *ui_Panel28;
lv_obj_t *ui_Panel27;
lv_obj_t *ui_Label28;
lv_obj_t *ui_Bar1;

// SCREEN: ui_newsScreen
void ui_newsScreen_screen_init(void);
lv_obj_t *ui_newsScreen;
lv_obj_t *ui_appTitlePanel1;
lv_obj_t *ui_appTitleName1;
void ui_event_appTitleIcon1(lv_event_t *e);
lv_obj_t *ui_appTitleIcon1;
lv_obj_t *ui_settingsMainPanel1;
lv_obj_t *ui_Panel25;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Image13;
lv_obj_t *ui_Label42;
lv_obj_t *ui_Panel29;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Panel31;
lv_obj_t *ui_Image14;
lv_obj_t *ui_Label40;
lv_obj_t *ui_Panel32;
lv_obj_t *ui_Label43;
lv_obj_t *ui_Panel33;
lv_obj_t *ui_Image15;
lv_obj_t *ui_Label44;
lv_obj_t *ui_Panel34;
lv_obj_t *ui_Label45;
lv_obj_t *ui_Panel35;
lv_obj_t *ui_Image16;
lv_obj_t *ui_Label46;
lv_obj_t *ui_Panel17;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Panel21;
lv_obj_t *ui_Image17;
lv_obj_t *ui_Label21;
lv_obj_t *ui_Panel22;
lv_obj_t *ui_Label22;
lv_obj_t *ui_Panel23;
lv_obj_t *ui_Image18;
lv_obj_t *ui_Label47;

void ui_event____initial_actions0(lv_event_t *e);
lv_obj_t *ui____initial_actions0;

void init_custom(void);

#ifdef MIN_BG_IMG
const lv_img_dsc_t *ui_imgset_img[5] = {&ui_img_img1_png, &ui_img_img2_png, &ui_img_img5_png, &ui_img_img6_png, &ui_img_img8_png};
#else
const lv_img_dsc_t *ui_imgset_img[10] = {&ui_img_img0_png, &ui_img_img1_png, &ui_img_img2_png, &ui_img_img3_png, &ui_img_img4_png, &ui_img_img5_png, &ui_img_img6_png, &ui_img_img7_png, &ui_img_img8_png, &ui_img_img9_png};
#endif

app_info_t apps[] = {
    {0xAC00, "Camera", &ui_img_camera_ic_png},
    {0xA900, "Edge", &ui_img_edge_ic_png},
    {0xAE00, "Files", &ui_img_file_ic_png},
    {0xA400, "Groove Music", &ui_img_groove_ic_png},
    {0xA200, "Messaging", &ui_img_message_ic_png},
    {0xA500, "News", &ui_img_news_ic_png},
    {0xA800, "Outlook Mail", &ui_img_outlook_ic_png},
    {0xA300, "People", &ui_img_people_ic_png},
    {0xA100, "Phone", &ui_img_phone_ic_png},
    {0xA600, "Photos", &ui_img_photos_ic_png},
    {0xA700, "Settings", &ui_img_wp_settings_png},
    {0xAD00, "Stars", &ui_img_stars_ic_png},
    {0xAA00, "Store", &ui_img_microsoft_ic_png},
    {0xAB00, "Tips", &ui_img_tips_ic_png},
};

start_tile_t tiles[] = {
    {{0xA100, "Phone", &ui_img_phone_ic_png}, false, NULL, CM_LIVE_NONE},
    {{0xA300, "People", &ui_img_people_ic_png}, true, NULL, CM_LIVE_NONE},
    {{0xA800, "Outlook Mail", &ui_img_outlook_ic_png}, true, NULL, CM_LIVE_NONE},
    {{0xA200, "Messaging", &ui_img_message_ic_png}, false, NULL, CM_LIVE_NONE},
    {{0xA700, "Settings", &ui_img_wp_settings_png}, false, NULL, CM_LIVE_NONE},
    {{0xA400, "Groove Music", &ui_img_groove_ic_png}, false, NULL, CM_LIVE_NONE},
    {{0xAB00, "Tips", &ui_img_tips_ic_png}, false, &ui_img_embedded_tile_png, CM_LIVE_HORIZONTAL},
    {{0xA500, "News", &ui_img_news_ic_png}, true, &ui_img_news_tile_png, CM_LIVE_VERTICAL},
    {{0xAC00, "Camera", &ui_img_camera_ic_png}, false, NULL, CM_LIVE_NONE},
    {{0xA600, "Photos", &ui_img_photos_ic_png}, false, &ui_img_photo_tile_png, CM_LIVE_VERTICAL},
    {{0xAD00, "Stars", &ui_img_stars_ic_png}, false, NULL, CM_LIVE_NONE},
    {{0xA900, "Edge", &ui_img_edge_ic_png}, false, NULL, CM_LIVE_NONE},
    {{0xAA00, "Store", &ui_img_microsoft_ic_png}, true, NULL, CM_LIVE_NONE},
    {{0xAE00, "Files", &ui_img_file_ic_png}, false, NULL, CM_LIVE_NONE},
};

settings_info_t settings[] = {
    {0xA701, "System", "Display, notifications, battery", &ui_img_wp_system_png},
    {0xA702, "Devices", "Bluetooth, printers, mouse", &ui_img_wp_devices_png},
    {0xA703, "Network", "WiFi, cellular, hotspot", &ui_img_wp_network_png},
    {0xA704, "Personalization", "Background, lockscreen, colors", &ui_img_wp_personalization_png},
    {0xA705, "Apps", "Uninstall, defaults", &ui_img_wp_apps_png},
    {0xA706, "Accounts", "Email, sync, family", &ui_img_wp_account_png},
    {0xA707, "Time & Language", "Speech, region, date", &ui_img_wp_time_png},
    {0xA708, "Privacy", "Location, camera, microphone", &ui_img_wp_privacy_png},
    {0xA709, "About", "Serial, version, reset", &ui_img_wp_about_png}};

quick_action actions[] = {
    {0x00C1, "Airplane", &ui_img_airplane_ic_png, true},
    {0x00C2, "Cellular", &ui_img_cellular_ic_png, true},
    {0x00C3, "WiFi", &ui_img_wifi_ic_png, true},
    {0x00C4, "Bluetooth", &ui_img_bluetooth_ic_png, true},
    {0x00C5, "Brightness", &ui_img_brightness_ic_png, false},
    {0x00C6, "Battery", &ui_img_battery_ic_png, true},
    {0x00C7, "Hotspot", &ui_img_hotspot_ic_png, true},
    {0x00C8, "Settings", &ui_img_settings_ic_png, false},
    {0x00C9, "VPN", &ui_img_vpn_ic_png, true},
    {0x00CA, "Location", &ui_img_location_ic_png, true},
};

accent_color_t colors[] = {
    {"Lime", 0xA4C400},
    {"Green", 0x60A917},
    {"Emerald", 0x00BA00},
    {"Teal", 0x00ABA9},
    {"Cyan", 0x1BA1E2},
    {"Cobalt", 0x0050EF},
    {"Indigo", 0x6A00FF},
    {"Violet", 0xAA00FF},
    {"Pink", 0xF472D0},
    {"Magenta", 0xD80073},
    {"Crimson", 0xA20025},
    {"Red", 0xE51400},
    {"Orange", 0xFA6800},
    {"Amber", 0xF0A30A},
    {"Yellow", 0xE3C800},
    {"Brown", 0x825A2C},
    {"Olive", 0x6D8764},
    {"Steel", 0x647687},
    {"Mauve", 0x76608A},
    {"Taupe", 0x87794E},
};

#define MAX_LIVE 10

live_obj_t live[MAX_LIVE];

lv_obj_t *start[30];
lv_obj_t *img_tint[50];
lv_obj_t *panels[50];
lv_obj_t *txtarea[10];

int current_live = 0;
int current_start = 0;
int current_img = 0;
int current_panel = 0;
int current_txta = 0;

bool tint_navbar = false;

lv_obj_t *bar;
lv_obj_t *bgSel;
lv_obj_t *startSl;
lv_obj_t *navSl;
lv_obj_t *navSw;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void closeNotificationPanel_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 0, -480);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
}

void openNotificationPanel_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -480, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
}

void liveTileVertical6_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 2000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 76, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 2000);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 42000);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 2000);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 2000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_1, 0, -76);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 6000);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 34000);
    lv_anim_set_repeat_count(&PropertyAnimation_1, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 10000);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);
    ui_anim_user_data_t *PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_2_user_data->target = TargetObject;
    PropertyAnimation_2_user_data->val = -1;
    lv_anim_t PropertyAnimation_2;
    lv_anim_init(&PropertyAnimation_2);
    lv_anim_set_time(&PropertyAnimation_2, 2000);
    lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_2, -76, -152);
    lv_anim_set_path_cb(&PropertyAnimation_2, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_2, delay + 10000);
    lv_anim_set_deleted_cb(&PropertyAnimation_2, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_2, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_2, 26000);
    lv_anim_set_repeat_count(&PropertyAnimation_2, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_2, 18000);
    lv_anim_set_early_apply(&PropertyAnimation_2, false);
    lv_anim_start(&PropertyAnimation_2);
    ui_anim_user_data_t *PropertyAnimation_3_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_3_user_data->target = TargetObject;
    PropertyAnimation_3_user_data->val = -1;
    lv_anim_t PropertyAnimation_3;
    lv_anim_init(&PropertyAnimation_3);
    lv_anim_set_time(&PropertyAnimation_3, 2000);
    lv_anim_set_user_data(&PropertyAnimation_3, PropertyAnimation_3_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_3, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_3, -152, -228);
    lv_anim_set_path_cb(&PropertyAnimation_3, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_3, delay + 14000);
    lv_anim_set_deleted_cb(&PropertyAnimation_3, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_3, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_3, 18000);
    lv_anim_set_repeat_count(&PropertyAnimation_3, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_3, 26000);
    lv_anim_set_early_apply(&PropertyAnimation_3, false);
    lv_anim_start(&PropertyAnimation_3);
    ui_anim_user_data_t *PropertyAnimation_4_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_4_user_data->target = TargetObject;
    PropertyAnimation_4_user_data->val = -1;
    lv_anim_t PropertyAnimation_4;
    lv_anim_init(&PropertyAnimation_4);
    lv_anim_set_time(&PropertyAnimation_4, 2000);
    lv_anim_set_user_data(&PropertyAnimation_4, PropertyAnimation_4_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_4, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_4, -228, -304);
    lv_anim_set_path_cb(&PropertyAnimation_4, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_4, delay + 18000);
    lv_anim_set_deleted_cb(&PropertyAnimation_4, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_4, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_4, 10000);
    lv_anim_set_repeat_count(&PropertyAnimation_4, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_4, 34000);
    lv_anim_set_early_apply(&PropertyAnimation_4, false);
    lv_anim_start(&PropertyAnimation_4);
    ui_anim_user_data_t *PropertyAnimation_5_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_5_user_data->target = TargetObject;
    PropertyAnimation_5_user_data->val = -1;
    lv_anim_t PropertyAnimation_5;
    lv_anim_init(&PropertyAnimation_5);
    lv_anim_set_time(&PropertyAnimation_5, 2000);
    lv_anim_set_user_data(&PropertyAnimation_5, PropertyAnimation_5_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_5, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_5, -304, -380);
    lv_anim_set_path_cb(&PropertyAnimation_5, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_5, delay + 22000);
    lv_anim_set_deleted_cb(&PropertyAnimation_5, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_5, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_5, 2000);
    lv_anim_set_repeat_count(&PropertyAnimation_5, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_5, 42000);
    lv_anim_set_early_apply(&PropertyAnimation_5, false);
    lv_anim_start(&PropertyAnimation_5);
}

void liveTileHorizontal5_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 2000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 100, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 2000);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 34000);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 2000);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 2000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_1, 0, -100);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 6000);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 26000);
    lv_anim_set_repeat_count(&PropertyAnimation_1, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 10000);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);
    ui_anim_user_data_t *PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_2_user_data->target = TargetObject;
    PropertyAnimation_2_user_data->val = -1;
    lv_anim_t PropertyAnimation_2;
    lv_anim_init(&PropertyAnimation_2);
    lv_anim_set_time(&PropertyAnimation_2, 2000);
    lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_2, -100, -200);
    lv_anim_set_path_cb(&PropertyAnimation_2, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_2, delay + 10000);
    lv_anim_set_deleted_cb(&PropertyAnimation_2, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_2, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_2, 18000);
    lv_anim_set_repeat_count(&PropertyAnimation_2, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_2, 18000);
    lv_anim_set_early_apply(&PropertyAnimation_2, false);
    lv_anim_start(&PropertyAnimation_2);
    ui_anim_user_data_t *PropertyAnimation_3_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_3_user_data->target = TargetObject;
    PropertyAnimation_3_user_data->val = -1;
    lv_anim_t PropertyAnimation_3;
    lv_anim_init(&PropertyAnimation_3);
    lv_anim_set_time(&PropertyAnimation_3, 2000);
    lv_anim_set_user_data(&PropertyAnimation_3, PropertyAnimation_3_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_3, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_3, -200, -300);
    lv_anim_set_path_cb(&PropertyAnimation_3, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_3, delay + 14000);
    lv_anim_set_deleted_cb(&PropertyAnimation_3, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_3, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_3, 10000);
    lv_anim_set_repeat_count(&PropertyAnimation_3, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_3, 26000);
    lv_anim_set_early_apply(&PropertyAnimation_3, false);
    lv_anim_start(&PropertyAnimation_3);
    ui_anim_user_data_t *PropertyAnimation_4_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_4_user_data->target = TargetObject;
    PropertyAnimation_4_user_data->val = -1;
    lv_anim_t PropertyAnimation_4;
    lv_anim_init(&PropertyAnimation_4);
    lv_anim_set_time(&PropertyAnimation_4, 2000);
    lv_anim_set_user_data(&PropertyAnimation_4, PropertyAnimation_4_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_4, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_4, -300, -400);
    lv_anim_set_path_cb(&PropertyAnimation_4, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_4, delay + 18000);
    lv_anim_set_deleted_cb(&PropertyAnimation_4, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_4, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_4, 2000);
    lv_anim_set_repeat_count(&PropertyAnimation_4, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_4, 34000);
    lv_anim_set_early_apply(&PropertyAnimation_4, false);
    lv_anim_start(&PropertyAnimation_4);
}

void cortanaPulse_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_width);
    lv_anim_set_values(&PropertyAnimation_0, 50, 30);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 1000);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 1000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_height);
    lv_anim_set_values(&PropertyAnimation_1, 50, 30);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 1000);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);
}

void closePanelDown_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 0, 480);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 500);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);
}

void openPanelUp_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 480, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 500);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);
}

///////////////////// HELPER ////////////////////

void show_alert(const char *title, const char *text)
{
    lv_label_set_text(ui_alertTitle, title);
    lv_label_set_text(ui_alertText, text);
    lv_obj_clear_flag(ui_alertPanel, LV_OBJ_FLAG_HIDDEN);
}

void register_live(live_obj_t l)
{
    if (current_live < MAX_LIVE)
    {
        live[current_live] = l;
        current_live++;
    }
}

void register_start(lv_obj_t *obj)
{
    if (current_start < 30)
    {
        start[current_start] = obj;
        current_start++;
    }
}

void register_img(lv_obj_t *obj)
{
    if (current_img < 50)
    {
        img_tint[current_img] = obj;
        current_img++;
    }
}

void register_panel(lv_obj_t *obj)
{
    if (current_panel < 50)
    {
        panels[current_panel] = obj;
        current_panel++;
    }
}

void register_txta(lv_obj_t *obj)
{
    if (current_txta < 10)
    {
        txtarea[current_txta] = obj;
        current_txta++;
    }
}

void launch_app(lv_event_t *e)
{
    uint64_t code = (uint64_t)lv_event_get_user_data(e);

    switch (code)
    {
    case 0xA700:
        _ui_screen_change(&ui_settingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_settingsScreen_screen_init);
        break;
    case 0xAD00:
        _ui_screen_change(&ui_starsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_starsScreen_screen_init);
        break;
    case 0xA500:
        _ui_screen_change(&ui_newsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_newsScreen_screen_init);
        break;
    case 0xAB00:
        for (int a = 0; a < (sizeof(apps) / sizeof(apps[0])); a++)
        {
            if (apps[a].code == code)
            {
                lv_label_set_text(ui_appTitleName, apps[a].name);
                lv_img_set_src(ui_appTitleIcon, apps[a].icon);
                break;
            }
        }

        _ui_screen_change(&ui_appScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_appScreen_screen_init);

        break;
    // case 0xA700:
    // break;
    default:
        show_alert("App error", "This app has not been setup. Nothing to launch");
        break;
    }
}

void launch_settings(lv_event_t *e)
{
    uint64_t code = (uint64_t)lv_event_get_user_data(e);

    
    lv_obj_add_flag(ui_personalizationPanel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_systemPanel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_settingsMainPanel, LV_OBJ_FLAG_HIDDEN);

    switch (code)
    {
    case 0xA700:
        /* code */
        lv_obj_clear_flag(ui_settingsMainPanel, LV_OBJ_FLAG_HIDDEN);
        break;
    case 0xA701:
        lv_obj_clear_flag(ui_systemPanel, LV_OBJ_FLAG_HIDDEN);
        break;
    case 0xA704:
        lv_obj_clear_flag(ui_personalizationPanel, LV_OBJ_FLAG_HIDDEN);
        break;
    default:
        lv_obj_clear_flag(ui_settingsMainPanel, LV_OBJ_FLAG_HIDDEN);
        show_alert("Settings error", "This setting is not available at the moment");
        return;
        break;
    }

    if (code != 0xA700)
    {
        for (int a = 0; a < (sizeof(settings) / sizeof(settings[0])); a++)
        {
            if (settings[a].code == code)
            {
                lv_img_set_src(ui_settingsAppIcon, settings[a].icon);
                lv_label_set_text(ui_settingsAppTitle, settings[a].title);
                break;
            }
        }
        lv_obj_clear_flag(ui_settingsBack, LV_OBJ_FLAG_HIDDEN);
    }
    else
    {
        lv_img_set_src(ui_settingsAppIcon, &ui_img_wp_settings_png);
        lv_label_set_text(ui_settingsAppTitle, "Settings");
        lv_obj_add_flag(ui_settingsBack, LV_OBJ_FLAG_HIDDEN);
    }
}

void action_event(lv_event_t *e)
{
    uint64_t code = (uint64_t)lv_event_get_user_data(e);
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    switch (code)
    {
    case 0x00C3:
        // wifi
        if (lv_obj_has_state(target, LV_STATE_CHECKED)){
            lv_obj_add_flag(ui_statusPanelWifi, LV_OBJ_FLAG_HIDDEN);
        } else {
            lv_obj_clear_flag(ui_statusPanelWifi, LV_OBJ_FLAG_HIDDEN);
        }
        break;
    case 0x00C4:
        // bt
        if (lv_obj_has_state(target, LV_STATE_CHECKED)){
            lv_obj_add_flag(ui_statusPanelBluetooth, LV_OBJ_FLAG_HIDDEN);
        } else {
            lv_obj_clear_flag(ui_statusPanelBluetooth, LV_OBJ_FLAG_HIDDEN);
        }
        break;
    case 0x00C8:
        // settings
        closeNotificationPanel_Animation(ui_notificationPanel, 0);
        lv_obj_clear_state(ui_notificationPanel, LV_STATE_CHECKED);
        _ui_screen_change(&ui_settingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_settingsScreen_screen_init);
        break;
    
    default:
        break;
    }

}

void theme_change(lv_event_t *e)
{
    uint32_t color = (uint32_t)((uint64_t)lv_event_get_user_data(e));

    setPrefInt("theme_color", color);

    lv_disp_t *display = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(display, lv_color_hex(color), lv_palette_main(LV_PALETTE_GREY), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(display, theme);

    for (int i = 0; i < current_start; i++)
    {
        lv_obj_set_style_bg_color(start[i], lv_color_hex(color), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    for (int j = 0; j < current_img; j++)
    {
        lv_obj_set_style_img_recolor(img_tint[j], lv_color_hex(color), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    for (int k = 0; k < current_panel; k++)
    {
        lv_obj_set_style_bg_color(panels[k], lv_color_hex(color), LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    for (int l = 0; l < current_txta; l++)
    {
        lv_obj_set_style_border_color(txtarea[l], lv_color_hex(color), LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    if (tint_navbar)
    {
        lv_obj_set_style_bg_color(ui_navPanel, lv_color_hex(color), LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(color), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea3, lv_color_hex(color), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cortanaIcon, lv_color_hex(color), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_cortanaIcon, lv_color_hex(color), LV_PART_MAIN | LV_STATE_DEFAULT);
}

void start_opacity(lv_event_t *e)
{
    lv_obj_t *target = lv_event_get_target(e);
    int32_t value = lv_slider_get_value(target);
    int32_t max = lv_slider_get_max_value(target);

    setPrefInt("start_opa", value);

    for (int i = 0; i < current_start; i++)
    {
        lv_obj_set_style_bg_opa(start[i], max - value, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

void navbar_opacity(lv_event_t *e)
{
    lv_obj_t *target = lv_event_get_target(e);
    int32_t value = lv_slider_get_value(target);
    int32_t max = lv_slider_get_max_value(target);
    int32_t min = lv_slider_get_min_value(target);
    setPrefInt("nav_opa", value);
    lv_obj_set_style_bg_opa(ui_navPanel, max - value + min, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void navbar_tint(lv_event_t *e)
{
    lv_obj_t *target = lv_event_get_target(e);
    tint_navbar = lv_obj_has_state(target, LV_STATE_CHECKED);
    setPrefBool("nav_tint", tint_navbar);

    if (tint_navbar)
    {
        lv_obj_set_style_bg_color(ui_navPanel, lv_theme_get_color_primary(target), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    else
    {
        lv_obj_set_style_bg_color(ui_navPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

void background_img(lv_event_t *e)
{
    uint64_t code = (uint64_t)lv_event_get_user_data(e);
    lv_obj_set_style_bg_img_src(ui_homeScreen, ui_imgset_img[code % (sizeof(ui_imgset_img) / sizeof(ui_imgset_img[0]))], LV_PART_MAIN | LV_STATE_DEFAULT);
    setPrefInt("bg_img", code);
}

void lockscreen_img(lv_event_t *e)
{
    uint64_t code = (uint64_t)lv_event_get_user_data(e);
    lv_obj_set_style_bg_img_src(ui_lockScreenPanel, ui_imgset_img[code % (sizeof(ui_imgset_img) / sizeof(ui_imgset_img[0]))], LV_PART_MAIN | LV_STATE_DEFAULT);
    setPrefInt("lock_img", code);
}

void background_select(lv_event_t *e)
{
    lv_obj_t *target = lv_event_get_target(e);
    uint16_t selected = lv_dropdown_get_selected(target);

    setPrefInt("bg_type", selected);

    if (selected == 0)
    {
        lv_obj_add_flag(ui_backgroundSelect, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_style_bg_img_src(ui_homeScreen, NULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    else
    {
        lv_obj_clear_flag(ui_backgroundSelect, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_style_bg_img_src(ui_homeScreen, ui_imgset_img[getPrefInt("bg_img", 5) % (sizeof(ui_imgset_img) / sizeof(ui_imgset_img[0]))], LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

void slider_val(lv_event_t *e)
{
    lv_obj_t *target = lv_event_get_target(e);
    int32_t value = lv_slider_get_value(target);

    cm_set_bar(bar, value, "%d%% Slider");
    
}

void brightness_slider(lv_event_t *e)
{
    lv_obj_t *target = lv_event_get_target(e);
    int32_t value = lv_slider_get_value(target);

    onBrightnessChange(value);

}

void timeout_select(lv_event_t *e)
{
    lv_obj_t *target = lv_event_get_target(e);
    uint16_t selected = lv_dropdown_get_selected(target);

    onTimeoutChange(selected);
}

///////////////////// FUNCTIONS ////////////////////
void ui_event_cortanaPanel(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM)
    {
        lv_indev_wait_release(lv_indev_get_act());
        lv_obj_clear_state(ui_cortanaPanel, LV_STATE_CHECKED);
        closePanelDown_Animation(ui_cortanaPanel, 0);
    }
}

void ui_event_Panel6(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_settingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_settingsScreen_screen_init);
    }
}

void ui_event_appListPanel(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        lv_obj_scroll_to_view(ui_appsListPanel, LV_ANIM_ON);
    }
}

void ui_event_alertbutton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_flag_modify(ui_alertPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_nav_home(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {

        if (lv_obj_has_state(ui_cortanaPanel, LV_STATE_CHECKED))
        {
            lv_obj_clear_state(ui_cortanaPanel, LV_STATE_CHECKED);
            closePanelDown_Animation(ui_cortanaPanel, 0);
        }

        lv_disp_t *display = lv_disp_get_default();
        lv_obj_t *actScr = lv_disp_get_scr_act(display);
        if (actScr == ui_homeScreen)
        {
            // if (!lv_obj_is_visible(ui_startPanel)){
            lv_obj_scroll_to_view(ui_startPanel, LV_ANIM_ON);
            // }
            return;
        }
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_homeScreen_screen_init);
    }
}

void ui_event_nav_back(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        if (lv_obj_has_state(ui_cortanaPanel, LV_STATE_CHECKED))
        {
            lv_obj_clear_state(ui_cortanaPanel, LV_STATE_CHECKED);
            closePanelDown_Animation(ui_cortanaPanel, 0);
            return;
        }

        lv_disp_t *display = lv_disp_get_default();
        lv_obj_t *actScr = lv_disp_get_scr_act(display);
        if (actScr == ui_homeScreen)
        {
            if (!lv_obj_is_visible(ui_startPanel))
            {
                lv_obj_scroll_to_view(ui_startPanel, LV_ANIM_ON);
                return;
            }
            openNotificationPanel_Animation(ui_lockScreenPanel, 0);
            return;
        }
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_homeScreen_screen_init);
    }
}

void ui_event_nav_search(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {

        if (lv_obj_has_state(ui_cortanaPanel, LV_STATE_CHECKED))
        {
            lv_obj_clear_state(ui_cortanaPanel, LV_STATE_CHECKED);
            closePanelDown_Animation(ui_cortanaPanel, 0);
        }
        else
        {
            lv_obj_add_state(ui_cortanaPanel, LV_STATE_CHECKED);
            openPanelUp_Animation(ui_cortanaPanel, 0);
        }
    }
}

void ui_event_screen_load(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOADED)
    {
        set_parent(target);
    }
}

void ui_event_Panel12(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_appScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_appScreen_screen_init);
    }
}

void ui_event_Panel11(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_newsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_newsScreen_screen_init);
    }
}

void ui_event_Panel15(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        // openNotificationPanel_Animation(ui_lockScreenPanel, 0);
        _ui_screen_change(&ui_starsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_starsScreen_screen_init);
    }
}

void ui_event_lockScreenPanel(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP)
    {
        lv_indev_wait_release(lv_indev_get_act());
        closeNotificationPanel_Animation(ui_lockScreenPanel, 0);
    }
}

void ui_event_notificationPanel(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP)
    {
        lv_indev_wait_release(lv_indev_get_act());
        closeNotificationPanel_Animation(ui_notificationPanel, 0);
        lv_obj_clear_state(ui_notificationPanel, LV_STATE_CHECKED);
    }
}

void ui_event_statusPanelRight(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        if (!lv_obj_has_state(ui_notificationPanel, LV_STATE_CHECKED)){
            openNotificationPanel_Animation(ui_notificationPanel, 0);
            lv_obj_add_state(ui_notificationPanel, LV_STATE_CHECKED);
        }
    }
}

void ui_event_appTitleIcon2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_homeScreen_screen_init);
    }
}

void ui_event_appTitleIcon(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_homeScreen_screen_init);
    }
}

void ui_event_genSwitch(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_checked_set_text_value(ui_genSwitchText, target, "On", "Off");
    }
}

void ui_event_appTitleIcon1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_homeScreen_screen_init);
    }
}

void ui_event____initial_actions0(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START)
    {
        _ui_basic_set_property(ui_lockScreenPanel, _UI_BASIC_PROPERTY_POSITION_Y, 0);
        // liveTileVertical6_Animation(ui_newsLiveImage, 2000);
        // liveTileVertical6_Animation(ui_photosLiveImage, 3700);
        // liveTileHorizontal5_Animation(ui_tipsLiveImage, 1300);

        for (int i = 0; i < current_live; i++)
        {
            live_obj_t lv = live[i];
            if (lv.dir == CM_LIVE_VERTICAL)
            {
                liveTileVertical6_Animation(lv.obj, lv_rand(1000 + (i * 1000), 2500 + (i * 1000)));
            }
            else
            {
                liveTileHorizontal5_Animation(lv.obj, lv_rand(2000 + (i * 1000), 3500 + (i * 1000)));
            }
        }
        cortanaPulse_Animation(ui_cortanaIcon, 1000);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_homeScreen_screen_init();
    ui_settingsScreen_screen_init();
    ui_appScreen_screen_init();
    ui_newsScreen_screen_init();
    ui_starsScreen_screen_init();

    init_custom();

    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_homeScreen);
}

///////////////////// EXTRA ////////////////////

void init_custom(void)
{
    // start tiles
    for (int a = 0; a < (sizeof(tiles) / sizeof(tiles[0])); a++)
    {
        cm_start_tile(tiles[a], register_live, launch_app, register_start);
    }

    lv_obj_set_parent(ui_allAppsPanel, ui_startPanel);

    // start app list
    for (int a = 0; a < (sizeof(apps) / sizeof(apps[0])); a++)
    {
        cm_app_list(apps[a], launch_app, register_panel);
    }

    // quick actions
    for (int a = 0; a < (sizeof(actions) / sizeof(actions[0])); a++)
    {
        cm_quick_action(ui_quickActionPanel, actions[a], action_event);
    }

    // settings main
    cm_create_text_area(ui_settingsMainPanel, "Find a setting", register_txta);
    for (int a = 0; a < (sizeof(settings) / sizeof(settings[0])); a++)
    {
        cm_settings_list(ui_settingsMainPanel, settings[a], launch_settings, register_img);
    }
    lv_obj_add_event_cb(ui_settingsBack, launch_settings, LV_EVENT_CLICKED, (void *)0xA700);

    // settings system
    cm_create_panel_space(ui_systemPanel, 10);
    cm_create_title(ui_systemPanel, "Display");
    cm_create_text(ui_systemPanel, "Brightness");
    cm_create_panel_space(ui_systemPanel, 5);
    cm_create_slider(ui_systemPanel, 200, 1, 255, brightness_slider);
    cm_create_panel_space(ui_systemPanel, 10);
    cm_create_text(ui_systemPanel, "Timeout");
    cm_create_dropdown(ui_systemPanel, "5 Seconds\n10 Seconds\n20 Seconds\n30 Seconds\nAlways On", 1, 150, timeout_select);

    // settings personalization
    cm_create_panel_space(ui_personalizationPanel, 10);
    cm_create_text(ui_personalizationPanel, "Accent Color");
    lv_obj_set_parent(ui_themePanel, ui_personalizationPanel);
    for (int a = 0; a < (sizeof(colors) / sizeof(colors[0])); a++)
    {
        cm_accent_color(ui_themePanel, colors[a], theme_change);
    }
    cm_create_panel_space(ui_personalizationPanel, 10);
    cm_create_text(ui_personalizationPanel, "Tile Opacity");
    cm_create_panel_space(ui_personalizationPanel, 5);
    startSl = cm_create_slider(ui_personalizationPanel, getPrefInt("start_opa", 200), 0, 255, start_opacity);
    cm_create_panel_space(ui_personalizationPanel, 10);
    cm_create_text(ui_personalizationPanel, "Background");
    bgSel = cm_create_dropdown(ui_personalizationPanel, "None\nPicture", getPrefInt("bg_type", 1), 150, background_select);
    lv_obj_set_parent(ui_backgroundSelect, ui_personalizationPanel);
    for (int a = 0; a < (sizeof(ui_imgset_img) / sizeof(ui_imgset_img[0])); a++)
    {
        cm_image_select(ui_backgroundSelect, ui_imgset_img[a], a, background_img);
    }
    cm_create_panel_space(ui_personalizationPanel, 10);
    cm_create_text(ui_personalizationPanel, "NavBar Opacity");
    cm_create_panel_space(ui_personalizationPanel, 5);
    navSl = cm_create_slider(ui_personalizationPanel, getPrefInt("nav_opa", 200), 20, 255, navbar_opacity);
    cm_create_panel_space(ui_personalizationPanel, 10);
    navSw = cm_create_switch(ui_personalizationPanel, "Navbar accent color", getPrefBool("nav_tint", false), navbar_tint);
    cm_create_panel_space(ui_personalizationPanel, 10);

    cm_create_text(ui_personalizationPanel, "Lockscreen");
    lv_obj_set_parent(ui_lockscreenSelect, ui_personalizationPanel);
    for (int a = 0; a < (sizeof(ui_imgset_img) / sizeof(ui_imgset_img[0])); a++)
    {
        cm_image_select(ui_lockscreenSelect, ui_imgset_img[a], a, lockscreen_img);
    }

    register_img(ui_settingsAppIcon);
    register_img(ui_settingsBack);

    // stars screen
    int stars = (sizeof(users) / sizeof(users[0]));
    lv_label_set_text_fmt(ui_Label7, "Total Stars: %d", stars);
    for (int i = 0; i < stars; i++)
    {
        cm_user_list(ui_stargazersPanel, users[i]);
    }
    register_img(ui_starsTitleIcon);

    register_img(ui_appTitleIcon1);
    register_img(ui_appTitleIcon);
    register_panel(ui_Panel30);
    register_txta(ui_alertDialogPanel);

    bar = cm_create_bar(ui_appMainPanel, 25, "%d%% Percent");
    cm_create_panel_space(ui_appMainPanel, 10);
    cm_create_slider(ui_appMainPanel, 0, 0, 100, slider_val);



    // Load saved preferences

    lv_obj_set_style_bg_img_src(ui_homeScreen, ui_imgset_img[getPrefInt("bg_img", 5) % (sizeof(ui_imgset_img) / sizeof(ui_imgset_img[0]))], LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_lockScreenPanel, ui_imgset_img[getPrefInt("lock_img", 2) % (sizeof(ui_imgset_img) / sizeof(ui_imgset_img[0]))], LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_event_t e;
    e.user_data = (void*)(uint64_t)getPrefInt("theme_color", 0x0050EF);
    theme_change(&e);

    e.target = navSl;
    e.user_data = (void*)(uint64_t)getPrefInt("nav_opa", 200);
    navbar_opacity(&e);

    e.target = startSl;
    e.user_data = (void*)(uint64_t)getPrefInt("start_opa", 200);
    start_opacity(&e);

    lv_dropdown_set_selected(bgSel, getPrefInt("bg_type", 1));
    e.target = bgSel;
    background_select(&e);

    if (getPrefBool("nav_tint", false)){
        lv_obj_add_state(navSw, LV_STATE_CHECKED);
    } else {
        lv_obj_clear_state(navSw, LV_STATE_CHECKED);
    }
    e.target = navSw;
    navbar_tint(&e);

    // e.user_data = (void*)(uint64_t)getPrefInt("start_opa", 200);
    // start_opacity(&e);


}
