// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: W10M

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void closeNotificationPanel_Animation(lv_obj_t * TargetObject, int delay);
void openNotificationPanel_Animation(lv_obj_t * TargetObject, int delay);
void liveTileVertical6_Animation(lv_obj_t * TargetObject, int delay);
void liveTileHorizontal5_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_homeScreen
void ui_homeScreen_screen_init(void);
lv_obj_t * ui_homeScreen;
lv_obj_t * ui_homePanel;
lv_obj_t * ui_startPanel;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label8;
void ui_event_Panel6(lv_event_t * e);
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Label10;
void ui_event_Panel12(lv_event_t * e);
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Label14;
lv_obj_t * ui_tipsLiveImage;
void ui_event_Panel11(lv_event_t * e);
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Label13;
lv_obj_t * ui_newsLiveImage;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Label12;
lv_obj_t * ui_photosLiveImage;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label11;
void ui_event_Panel15(lv_event_t * e);
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Label18;
lv_obj_t * ui_allAppsPanel;
lv_obj_t * ui_allAppsLabel;
lv_obj_t * ui_allAppsIcon;
lv_obj_t * ui_appsListPanel;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Panel19;
lv_obj_t * ui_Panel20;
lv_obj_t * ui_Label20;
lv_obj_t * ui_navPanel;
lv_obj_t * ui_navBack;
lv_obj_t * ui_navHome;
lv_obj_t * ui_navSearch;
void ui_event_lockScreenPanel(lv_event_t * e);
lv_obj_t * ui_lockScreenPanel;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Label39;
void ui_event_notificationPanel(lv_event_t * e);
lv_obj_t * ui_notificationPanel;
lv_obj_t * ui_quickActionPanel;
lv_obj_t * ui_Button4;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Button5;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Button6;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Button7;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Button8;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Button3;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Button9;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Label35;
lv_obj_t * ui_Button10;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Button11;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Panel30;
lv_obj_t * ui_Label38;
lv_obj_t * ui_statusPanel;
lv_obj_t * ui_statusPanelLeft;
lv_obj_t * ui_statusPanelCellular;
lv_obj_t * ui_statusPanelWifi;
lv_obj_t * ui_statusPanelBluetooth;
void ui_event_statusPanelRight(lv_event_t * e);
lv_obj_t * ui_statusPanelRight;
lv_obj_t * ui_statusPanelBattery;
lv_obj_t * ui_statusPanelTime;


// SCREEN: ui_settingsScreen
void ui_settingsScreen_screen_init(void);
lv_obj_t * ui_settingsScreen;
lv_obj_t * ui_appTitlePanel2;
lv_obj_t * ui_appTitleName2;
void ui_event_appTitleIcon2(lv_event_t * e);
lv_obj_t * ui_appTitleIcon2;
lv_obj_t * ui_settingsMainPanel;
lv_obj_t * ui_TextArea1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;


// SCREEN: ui_appScreen
void ui_appScreen_screen_init(void);
lv_obj_t * ui_appScreen;
lv_obj_t * ui_appTitlePanel;
lv_obj_t * ui_appTitleName;
void ui_event_appTitleIcon(lv_event_t * e);
lv_obj_t * ui_appTitleIcon;
lv_obj_t * ui_appMainPanel;
lv_obj_t * ui_Label23;
lv_obj_t * ui_genSwitchPanel;
void ui_event_genSwitch(lv_event_t * e);
lv_obj_t * ui_genSwitch;
lv_obj_t * ui_genSwitchText;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Panel28;
lv_obj_t * ui_Panel27;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Bar1;


// SCREEN: ui_newsScreen
void ui_newsScreen_screen_init(void);
lv_obj_t * ui_newsScreen;
lv_obj_t * ui_appTitlePanel1;
lv_obj_t * ui_appTitleName1;
void ui_event_appTitleIcon1(lv_event_t * e);
lv_obj_t * ui_appTitleIcon1;
lv_obj_t * ui_settingsMainPanel1;
lv_obj_t * ui_Panel25;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Label42;
lv_obj_t * ui_Panel29;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Panel31;
lv_obj_t * ui_Image14;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Panel32;
lv_obj_t * ui_Label43;
lv_obj_t * ui_Panel33;
lv_obj_t * ui_Image15;
lv_obj_t * ui_Label44;
lv_obj_t * ui_Panel34;
lv_obj_t * ui_Label45;
lv_obj_t * ui_Panel35;
lv_obj_t * ui_Image16;
lv_obj_t * ui_Label46;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Panel21;
lv_obj_t * ui_Image17;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Panel22;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Panel23;
lv_obj_t * ui_Image18;
lv_obj_t * ui_Label47;
void ui_event____initial_actions0(lv_event_t * e);
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_img[10] = {&ui_img_img0_png, &ui_img_img1_png, &ui_img_img2_png, &ui_img_img3_png, &ui_img_img4_png, &ui_img_img5_png, &ui_img_img6_png, &ui_img_img7_png, &ui_img_img8_png, &ui_img_img9_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void closeNotificationPanel_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 0, -480);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void openNotificationPanel_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -480, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void liveTileVertical6_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 2000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 76, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 2000);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 42000);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 2000);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 2000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_1, 0, -76);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 6000);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 34000);
    lv_anim_set_repeat_count(&PropertyAnimation_1, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 10000);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);
    ui_anim_user_data_t * PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_2_user_data->target = TargetObject;
    PropertyAnimation_2_user_data->val = -1;
    lv_anim_t PropertyAnimation_2;
    lv_anim_init(&PropertyAnimation_2);
    lv_anim_set_time(&PropertyAnimation_2, 2000);
    lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_2, -76, -152);
    lv_anim_set_path_cb(&PropertyAnimation_2, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_2, delay + 10000);
    lv_anim_set_deleted_cb(&PropertyAnimation_2, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_2, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_2, 26000);
    lv_anim_set_repeat_count(&PropertyAnimation_2, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_2, 18000);
    lv_anim_set_early_apply(&PropertyAnimation_2, false);
    lv_anim_start(&PropertyAnimation_2);
    ui_anim_user_data_t * PropertyAnimation_3_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_3_user_data->target = TargetObject;
    PropertyAnimation_3_user_data->val = -1;
    lv_anim_t PropertyAnimation_3;
    lv_anim_init(&PropertyAnimation_3);
    lv_anim_set_time(&PropertyAnimation_3, 2000);
    lv_anim_set_user_data(&PropertyAnimation_3, PropertyAnimation_3_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_3, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_3, -152, -228);
    lv_anim_set_path_cb(&PropertyAnimation_3, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_3, delay + 14000);
    lv_anim_set_deleted_cb(&PropertyAnimation_3, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_3, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_3, 18000);
    lv_anim_set_repeat_count(&PropertyAnimation_3, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_3, 26000);
    lv_anim_set_early_apply(&PropertyAnimation_3, false);
    lv_anim_start(&PropertyAnimation_3);
    ui_anim_user_data_t * PropertyAnimation_4_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_4_user_data->target = TargetObject;
    PropertyAnimation_4_user_data->val = -1;
    lv_anim_t PropertyAnimation_4;
    lv_anim_init(&PropertyAnimation_4);
    lv_anim_set_time(&PropertyAnimation_4, 2000);
    lv_anim_set_user_data(&PropertyAnimation_4, PropertyAnimation_4_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_4, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_4, -228, -304);
    lv_anim_set_path_cb(&PropertyAnimation_4, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_4, delay + 18000);
    lv_anim_set_deleted_cb(&PropertyAnimation_4, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_4, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_4, 10000);
    lv_anim_set_repeat_count(&PropertyAnimation_4, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_4, 34000);
    lv_anim_set_early_apply(&PropertyAnimation_4, false);
    lv_anim_start(&PropertyAnimation_4);
    ui_anim_user_data_t * PropertyAnimation_5_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_5_user_data->target = TargetObject;
    PropertyAnimation_5_user_data->val = -1;
    lv_anim_t PropertyAnimation_5;
    lv_anim_init(&PropertyAnimation_5);
    lv_anim_set_time(&PropertyAnimation_5, 2000);
    lv_anim_set_user_data(&PropertyAnimation_5, PropertyAnimation_5_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_5, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_5, -304, -380);
    lv_anim_set_path_cb(&PropertyAnimation_5, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_5, delay + 22000);
    lv_anim_set_deleted_cb(&PropertyAnimation_5, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_5, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_5, 2000);
    lv_anim_set_repeat_count(&PropertyAnimation_5, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_5, 42000);
    lv_anim_set_early_apply(&PropertyAnimation_5, false);
    lv_anim_start(&PropertyAnimation_5);

}
void liveTileHorizontal5_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 2000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 100, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 2000);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 34000);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 2000);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 2000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_1, 0, -100);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 6000);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 26000);
    lv_anim_set_repeat_count(&PropertyAnimation_1, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 10000);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);
    ui_anim_user_data_t * PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_2_user_data->target = TargetObject;
    PropertyAnimation_2_user_data->val = -1;
    lv_anim_t PropertyAnimation_2;
    lv_anim_init(&PropertyAnimation_2);
    lv_anim_set_time(&PropertyAnimation_2, 2000);
    lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_2, -100, -200);
    lv_anim_set_path_cb(&PropertyAnimation_2, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_2, delay + 10000);
    lv_anim_set_deleted_cb(&PropertyAnimation_2, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_2, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_2, 18000);
    lv_anim_set_repeat_count(&PropertyAnimation_2, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_2, 18000);
    lv_anim_set_early_apply(&PropertyAnimation_2, false);
    lv_anim_start(&PropertyAnimation_2);
    ui_anim_user_data_t * PropertyAnimation_3_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_3_user_data->target = TargetObject;
    PropertyAnimation_3_user_data->val = -1;
    lv_anim_t PropertyAnimation_3;
    lv_anim_init(&PropertyAnimation_3);
    lv_anim_set_time(&PropertyAnimation_3, 2000);
    lv_anim_set_user_data(&PropertyAnimation_3, PropertyAnimation_3_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_3, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_3, -200, -300);
    lv_anim_set_path_cb(&PropertyAnimation_3, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_3, delay + 14000);
    lv_anim_set_deleted_cb(&PropertyAnimation_3, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_3, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_3, 10000);
    lv_anim_set_repeat_count(&PropertyAnimation_3, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_3, 26000);
    lv_anim_set_early_apply(&PropertyAnimation_3, false);
    lv_anim_start(&PropertyAnimation_3);
    ui_anim_user_data_t * PropertyAnimation_4_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_4_user_data->target = TargetObject;
    PropertyAnimation_4_user_data->val = -1;
    lv_anim_t PropertyAnimation_4;
    lv_anim_init(&PropertyAnimation_4);
    lv_anim_set_time(&PropertyAnimation_4, 2000);
    lv_anim_set_user_data(&PropertyAnimation_4, PropertyAnimation_4_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_4, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_4, -300, -400);
    lv_anim_set_path_cb(&PropertyAnimation_4, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_4, delay + 18000);
    lv_anim_set_deleted_cb(&PropertyAnimation_4, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_4, 2000);
    lv_anim_set_playback_delay(&PropertyAnimation_4, 2000);
    lv_anim_set_repeat_count(&PropertyAnimation_4, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_4, 34000);
    lv_anim_set_early_apply(&PropertyAnimation_4, false);
    lv_anim_start(&PropertyAnimation_4);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Panel6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_settingsScreen_screen_init);
    }
}
void ui_event_Panel12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_appScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_appScreen_screen_init);
    }
}
void ui_event_Panel11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_newsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_newsScreen_screen_init);
    }
}
void ui_event_Panel15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        openNotificationPanel_Animation(ui_lockScreenPanel, 0);
    }
}
void ui_event_lockScreenPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        closeNotificationPanel_Animation(ui_lockScreenPanel, 0);
    }
}
void ui_event_notificationPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        closeNotificationPanel_Animation(ui_notificationPanel, 0);
    }
}
void ui_event_statusPanelRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        openNotificationPanel_Animation(ui_notificationPanel, 0);
    }
}
void ui_event_appTitleIcon2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_homeScreen_screen_init);
    }
}
void ui_event_appTitleIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_homeScreen_screen_init);
    }
}
void ui_event_genSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_checked_set_text_value(ui_genSwitchText, target, "On", "Off");
    }
}
void ui_event_appTitleIcon1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_homeScreen_screen_init);
    }
}
void ui_event____initial_actions0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_basic_set_property(ui_lockScreenPanel, _UI_BASIC_PROPERTY_POSITION_Y,  0);
        liveTileVertical6_Animation(ui_newsLiveImage, 2000);
        liveTileVertical6_Animation(ui_photosLiveImage, 3700);
        liveTileHorizontal5_Animation(ui_tipsLiveImage, 1300);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_homeScreen_screen_init();
    ui_settingsScreen_screen_init();
    ui_appScreen_screen_init();
    ui_newsScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_homeScreen);
}
