// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: W10M

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif


void onRefreshWifi();
void onOpenNetworks();
void onConnectWifi();

void onLoadTestApp();
void onWifiStateChange(int state);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
