// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: W10M

#include "../ui.h"

void ui_homeScreen_screen_init(void)
{
    ui_homeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_homeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_homeScreen, &ui_img_img5_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homePanel = lv_obj_create(ui_homeScreen);
    lv_obj_set_width(ui_homePanel, 320);
    lv_obj_set_height(ui_homePanel, 480);
    lv_obj_set_align(ui_homePanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_homePanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_homePanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_homePanel, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_homePanel, LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_ELASTIC);      /// Flags
    lv_obj_set_scrollbar_mode(ui_homePanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_homePanel, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_dir(ui_homePanel, LV_DIR_HOR);
    lv_obj_set_style_radius(ui_homePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_homePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_homePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_homePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_homePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_homePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_homePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_homePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_homePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startPanel = lv_obj_create(ui_homePanel);
    lv_obj_set_width(ui_startPanel, 320);
    lv_obj_set_height(ui_startPanel, 480);
    lv_obj_set_align(ui_startPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_startPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_startPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_state(ui_startPanel, LV_STATE_EDITED);       /// States
    lv_obj_add_flag(ui_startPanel, LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_clear_flag(ui_startPanel, LV_OBJ_FLAG_SCROLL_ONE);
    lv_obj_set_scrollbar_mode(ui_startPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_startPanel, LV_DIR_VER);
    lv_obj_set_style_radius(ui_startPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_startPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_startPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_startPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_startPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_startPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_startPanel, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_startPanel, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_startPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_startPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_allAppsPanel = lv_obj_create(ui_startPanel);
    lv_obj_set_width(ui_allAppsPanel, 310);
    lv_obj_set_height(ui_allAppsPanel, 30);
    lv_obj_set_x(ui_allAppsPanel, -28);
    lv_obj_set_y(ui_allAppsPanel, -53);
    lv_obj_set_align(ui_allAppsPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_allAppsPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_allAppsPanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_allAppsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_allAppsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_allAppsPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_allAppsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_allAppsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_allAppsPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_allAppsPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_allAppsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_allAppsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_allAppsLabel = lv_label_create(ui_allAppsPanel);
    lv_obj_set_width(ui_allAppsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_allAppsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_allAppsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_allAppsLabel, "All apps ");

    ui_allAppsIcon = lv_img_create(ui_allAppsPanel);
    lv_img_set_src(ui_allAppsIcon, &ui_img_wp_next_png);
    lv_obj_set_width(ui_allAppsIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_allAppsIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_allAppsIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_allAppsIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_allAppsIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_appsListPanel = lv_obj_create(ui_homePanel);
    lv_obj_set_width(ui_appsListPanel, 320);
    lv_obj_set_height(ui_appsListPanel, 480);
    lv_obj_set_align(ui_appsListPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_appsListPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_appsListPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_appsListPanel, LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_clear_flag(ui_appsListPanel, LV_OBJ_FLAG_SCROLL_ONE);
    lv_obj_set_scrollbar_mode(ui_appsListPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_appsListPanel, LV_DIR_VER);
    lv_obj_set_style_radius(ui_appsListPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_appsListPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_appsListPanel, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_appsListPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_appsListPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_appsListPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_appsListPanel, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_appsListPanel, 70, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_cortanaPanel = lv_obj_create(ui_homeScreen);
    lv_obj_set_width(ui_cortanaPanel, 320);
    lv_obj_set_height(ui_cortanaPanel, 480);
    lv_obj_set_x(ui_cortanaPanel, 0);
    lv_obj_set_y(ui_cortanaPanel, 480);
    lv_obj_set_align(ui_cortanaPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_cortanaPanel, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_cortanaPanel, LV_OBJ_FLAG_CHECKABLE);
    lv_obj_set_style_radius(ui_cortanaPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cortanaPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cortanaPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cortanaPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea3 = lv_textarea_create(ui_cortanaPanel);
    lv_obj_set_width(ui_TextArea3, 300);
    lv_obj_set_height(ui_TextArea3, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea3, 0);
    lv_obj_set_y(ui_TextArea3, -40);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_BOTTOM_MID);
    lv_textarea_set_placeholder_text(ui_TextArea3, "How can i help you?");
    lv_obj_set_style_radius(ui_TextArea3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea3, lv_color_hex(0x70A2EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea3, 150, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label6 = lv_label_create(ui_cortanaPanel);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 8);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Hi there, I'm Cortana");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x0F6DFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cortanaIcon = lv_obj_create(ui_cortanaPanel);
    lv_obj_set_width(ui_cortanaIcon, 50);
    lv_obj_set_height(ui_cortanaIcon, 50);
    lv_obj_set_x(ui_cortanaIcon, 0);
    lv_obj_set_y(ui_cortanaIcon, -70);
    lv_obj_set_align(ui_cortanaIcon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cortanaIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cortanaIcon, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cortanaIcon, lv_color_hex(0xB1D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cortanaIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cortanaIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_cortanaIcon, lv_color_hex(0x2A98FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_cortanaIcon, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_cortanaIcon, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_cortanaIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navPanelListener = lv_obj_create(ui_homeScreen);
    lv_obj_set_width(ui_navPanelListener, 320);
    lv_obj_set_height(ui_navPanelListener, 40);
    lv_obj_set_align(ui_navPanelListener, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_navPanelListener, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_navPanelListener, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_navPanelListener, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_navPanelListener, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_navPanelListener, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_navPanelListener, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_navPanelListener, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_navPanelListener, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_navPanelListener, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_navPanelListener, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_navPanelListener, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navPanel = lv_obj_create(ui_homeScreen);
    lv_obj_set_width(ui_navPanel, 320);
    lv_obj_set_height(ui_navPanel, 40);
    lv_obj_set_align(ui_navPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_navPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_navPanel, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_navPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_navPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_navPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_navPanel, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_navPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_navPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_navPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_navPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_navPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navBack = lv_obj_create(ui_navPanel);
    lv_obj_set_width(ui_navBack, 80);
    lv_obj_set_height(ui_navBack, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_navBack, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_navBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_navBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_navBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_navBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_navBack, &ui_img_wp_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_navBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navHome = lv_obj_create(ui_navPanel);
    lv_obj_set_width(ui_navHome, 80);
    lv_obj_set_height(ui_navHome, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_navHome, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_navHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_navHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_navHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_navHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_navHome, &ui_img_windows_logo_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_navHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navSearch = lv_obj_create(ui_navPanel);
    lv_obj_set_width(ui_navSearch, 80);
    lv_obj_set_height(ui_navSearch, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_navSearch, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_navSearch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_navSearch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_navSearch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_navSearch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_navSearch, &ui_img_wp_search_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_navSearch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lockScreenPanel = lv_obj_create(ui_homeScreen);
    lv_obj_set_width(ui_lockScreenPanel, 320);
    lv_obj_set_height(ui_lockScreenPanel, 480);
    lv_obj_set_x(ui_lockScreenPanel, 0);
    lv_obj_set_y(ui_lockScreenPanel, -480);
    lv_obj_set_align(ui_lockScreenPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lockScreenPanel, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lockScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lockScreenPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lockScreenPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_lockScreenPanel, &ui_img_img2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lockScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_lockScreenPanel);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 15);
    lv_obj_set_y(ui_Label41, 75);
    lv_obj_set_align(ui_Label41, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label41, "12:00");
    lv_obj_set_style_text_font(ui_Label41, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_lockScreenPanel);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, 15);
    lv_obj_set_y(ui_Label39, 123);
    lv_obj_set_align(ui_Label39, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label39, "Wednesday, August 7");
    lv_obj_set_style_text_font(ui_Label39, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_notificationPanel = lv_obj_create(ui_homeScreen);
    lv_obj_set_width(ui_notificationPanel, 320);
    lv_obj_set_height(ui_notificationPanel, 480);
    lv_obj_set_x(ui_notificationPanel, 0);
    lv_obj_set_y(ui_notificationPanel, -480);
    lv_obj_set_align(ui_notificationPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_notificationPanel, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_notificationPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_notificationPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_notificationPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_notificationPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_notificationPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_notificationPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_notificationPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_notificationPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_quickActionPanel = lv_obj_create(ui_notificationPanel);
    lv_obj_set_width(ui_quickActionPanel, 320);
    lv_obj_set_height(ui_quickActionPanel, 103);
    lv_obj_set_x(ui_quickActionPanel, 0);
    lv_obj_set_y(ui_quickActionPanel, 30);
    lv_obj_set_align(ui_quickActionPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_quickActionPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_quickActionPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_quickActionPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_quickActionPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_quickActionPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_quickActionPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_quickActionPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_quickActionPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_quickActionPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_quickActionPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_quickActionPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_quickActionPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_quickActionPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Panel30 = lv_obj_create(ui_notificationPanel);
    lv_obj_set_width(ui_Panel30, 320);
    lv_obj_set_height(ui_Panel30, 10);
    lv_obj_set_align(ui_Panel30, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Panel30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel30, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel30, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_Panel30);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label38, "____");

    ui_statusPanel = lv_obj_create(ui_homeScreen);
    lv_obj_set_width(ui_statusPanel, 320);
    lv_obj_set_height(ui_statusPanel, 20);
    lv_obj_set_align(ui_statusPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_statusPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_statusPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statusPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_statusPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_statusPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_statusPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_statusPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_statusPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusPanelLeft = lv_obj_create(ui_statusPanel);
    lv_obj_set_width(ui_statusPanelLeft, 320);
    lv_obj_set_height(ui_statusPanelLeft, 20);
    lv_obj_set_align(ui_statusPanelLeft, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_statusPanelLeft, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_statusPanelLeft, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_statusPanelLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_statusPanelLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statusPanelLeft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusPanelLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_statusPanelLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusCellularBar = lv_bar_create(ui_statusPanelLeft);
    lv_bar_set_range(ui_statusCellularBar, 0, 10);
    lv_bar_set_value(ui_statusCellularBar, 4, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_statusCellularBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_statusCellularBar, 16);
    lv_obj_set_height(ui_statusCellularBar, 16);
    lv_obj_set_align(ui_statusCellularBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_statusCellularBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statusCellularBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusCellularBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_statusCellularBar, &ui_img_cellular_ic_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_statusCellularBar, lv_color_hex(0x383838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_statusCellularBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_statusCellularBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statusCellularBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusCellularBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_statusCellularBar, &ui_img_cellular_ic_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_statusPanelWifi = lv_img_create(ui_statusPanelLeft);
    lv_img_set_src(ui_statusPanelWifi, &ui_img_wifi_ic_png);
    lv_obj_set_width(ui_statusPanelWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusPanelWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_statusPanelWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_statusPanelWifi, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_statusPanelWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_statusPanelBluetooth = lv_img_create(ui_statusPanelLeft);
    lv_img_set_src(ui_statusPanelBluetooth, &ui_img_bluetooth_ic_png);
    lv_obj_set_width(ui_statusPanelBluetooth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusPanelBluetooth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_statusPanelBluetooth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_statusPanelBluetooth, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_statusPanelBluetooth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_statusPanelRight = lv_obj_create(ui_statusPanel);
    lv_obj_set_width(ui_statusPanelRight, 320);
    lv_obj_set_height(ui_statusPanelRight, 20);
    lv_obj_set_align(ui_statusPanelRight, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_statusPanelRight, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_statusPanelRight, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_statusPanelRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_statusPanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statusPanelRight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusPanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_statusPanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusPanelBattery = lv_img_create(ui_statusPanelRight);
    lv_img_set_src(ui_statusPanelBattery, &ui_img_battery_ic_png);
    lv_obj_set_width(ui_statusPanelBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusPanelBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_statusPanelBattery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_statusPanelBattery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_statusPanelBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_statusPanelTime = lv_label_create(ui_statusPanelRight);
    lv_obj_set_width(ui_statusPanelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusPanelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_statusPanelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_statusPanelTime, "20:21");
    lv_obj_set_style_text_font(ui_statusPanelTime, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alertPanel = lv_obj_create(ui_homeScreen);
    lv_obj_set_width(ui_alertPanel, 320);
    lv_obj_set_height(ui_alertPanel, 480);
    lv_obj_set_align(ui_alertPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_alertPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_alertPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_alertPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_alertPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alertPanel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_alertPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alertDialogPanel = lv_obj_create(ui_alertPanel);
    lv_obj_set_width(ui_alertDialogPanel, 250);
    lv_obj_set_height(ui_alertDialogPanel, LV_SIZE_CONTENT);    /// 154
    lv_obj_set_align(ui_alertDialogPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_alertDialogPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_alertDialogPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_alertDialogPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_alertDialogPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_alertDialogPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alertDialogPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_alertDialogPanel, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_alertDialogPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alertTitle = lv_label_create(ui_alertDialogPanel);
    lv_obj_set_width(ui_alertTitle, 220);
    lv_obj_set_height(ui_alertTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_alertTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alertTitle, "Alert Title");
    lv_obj_set_style_text_align(ui_alertTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_alertTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_alertTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_alertTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_alertTitle, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_alertTitle, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_alertTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_alertTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_alertTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_alertTitle, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alertText = lv_label_create(ui_alertDialogPanel);
    lv_obj_set_width(ui_alertText, 220);   /// 1
    lv_obj_set_height(ui_alertText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_alertText, LV_ALIGN_CENTER);
    lv_obj_set_style_pad_left(ui_alertText, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_alertText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_alertText, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_alertText, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alertbutton = lv_btn_create(ui_alertDialogPanel);
    lv_obj_set_width(ui_alertbutton, 100);
    lv_obj_set_height(ui_alertbutton, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_alertbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_alertbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_alertbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_alertbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alertbuttonText = lv_label_create(ui_alertbutton);
    lv_obj_set_width(ui_alertbuttonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alertbuttonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_alertbuttonText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alertbuttonText, "Close");



    lv_obj_add_event_cb(ui_alertbutton, ui_event_alertbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lockScreenPanel, ui_event_lockScreenPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_notificationPanel, ui_event_notificationPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_statusPanelRight, ui_event_statusPanelRight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cortanaPanel, ui_event_cortanaPanel, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_allAppsPanel, ui_event_appListPanel, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_navBack, ui_event_nav_back, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_navHome, ui_event_nav_home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_navSearch, ui_event_nav_search, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_homeScreen, ui_event_screen_load, LV_EVENT_SCREEN_LOADED, NULL);

}
