// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: W10M

#include "../ui.h"

void ui_settingsScreen_screen_init(void)
{
    ui_settingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_appTitlePanel2 = lv_obj_create(ui_settingsScreen);
    lv_obj_set_width(ui_appTitlePanel2, 320);
    lv_obj_set_height(ui_appTitlePanel2, 70);
    lv_obj_set_align(ui_appTitlePanel2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_appTitlePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_appTitlePanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_appTitlePanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_appTitleName2 = lv_label_create(ui_appTitlePanel2);
    lv_obj_set_width(ui_appTitleName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_appTitleName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_appTitleName2, 52);
    lv_obj_set_y(ui_appTitleName2, 10);
    lv_obj_set_align(ui_appTitleName2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_appTitleName2, "Settings");
    lv_obj_set_style_text_font(ui_appTitleName2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_appTitleIcon2 = lv_img_create(ui_appTitlePanel2);
    lv_img_set_src(ui_appTitleIcon2, &ui_img_wp_settings_png);
    lv_obj_set_width(ui_appTitleIcon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_appTitleIcon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_appTitleIcon2, 10);
    lv_obj_set_y(ui_appTitleIcon2, 10);
    lv_obj_set_align(ui_appTitleIcon2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_appTitleIcon2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_appTitleIcon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_appTitleIcon2, lv_color_hex(0x2062E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_appTitleIcon2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsMainPanel = lv_obj_create(ui_settingsScreen);
    lv_obj_set_width(ui_settingsMainPanel, 320);
    lv_obj_set_height(ui_settingsMainPanel, 410);
    lv_obj_set_x(ui_settingsMainPanel, 0);
    lv_obj_set_y(ui_settingsMainPanel, 70);
    lv_obj_set_align(ui_settingsMainPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_settingsMainPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_settingsMainPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_settingsMainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_settingsMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settingsMainPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_settingsMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_settingsMainPanel);
    lv_obj_set_width(ui_TextArea1, 300);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea1, 0);
    lv_obj_set_y(ui_TextArea1, -145);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Find a setting");
    lv_obj_set_style_radius(ui_TextArea1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0x70A2EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Panel2 = lv_obj_create(ui_settingsMainPanel);
    lv_obj_set_width(ui_Panel2, 320);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -97);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_Image1, &ui_img_wp_system_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 5);
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_align(ui_Image1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image1, lv_color_hex(0x2D87E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 50);
    lv_obj_set_y(ui_Label3, 10);
    lv_obj_set_align(ui_Label3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label3, "Display, notifications, battery");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 50);
    lv_obj_set_y(ui_Label4, -12);
    lv_obj_set_align(ui_Label4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label4, "System");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_appTitleIcon2, ui_event_appTitleIcon2, LV_EVENT_ALL, NULL);

}
