// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: W10M

#include "../ui.h"

void ui_thermalScreen_screen_init(void)
{
    ui_thermalScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_thermalScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_thermalTitlePanel = lv_obj_create(ui_thermalScreen);
    lv_obj_set_width(ui_thermalTitlePanel, 320);
    lv_obj_set_height(ui_thermalTitlePanel, 70);
    lv_obj_set_align(ui_thermalTitlePanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_thermalTitlePanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_thermalTitlePanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_thermalTitlePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_thermalTitlePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_thermalTitlePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_thermalTitlePanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_thermalTitlePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_thermalTitlePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_thermalTitlePanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_thermalTitlePanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_thermalTitlePanel, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_thermalAppIcon = lv_img_create(ui_thermalTitlePanel);
    lv_img_set_src(ui_thermalAppIcon, &ui_img_camera_ic_png);
    lv_obj_set_width(ui_thermalAppIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_thermalAppIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_thermalAppIcon, 10);
    lv_obj_set_y(ui_thermalAppIcon, 10);
    lv_obj_set_align(ui_thermalAppIcon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_thermalAppIcon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_thermalAppIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_thermalAppIcon, lv_color_hex(0x2062E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_thermalAppIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_thermalAppTitle = lv_label_create(ui_thermalTitlePanel);
    lv_obj_set_width(ui_thermalAppTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_thermalAppTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_thermalAppTitle, 52);
    lv_obj_set_y(ui_thermalAppTitle, 10);
    lv_obj_set_align(ui_thermalAppTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_thermalAppTitle, "Thermal IR");
    lv_obj_set_style_text_font(ui_thermalAppTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_thermalPanel = lv_obj_create(ui_thermalScreen);
    lv_obj_set_width(ui_thermalPanel, 320);
    lv_obj_set_height(ui_thermalPanel, 410);
    lv_obj_set_x(ui_thermalPanel, 0);
    lv_obj_set_y(ui_thermalPanel, 70);
    lv_obj_set_align(ui_thermalPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_thermalPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_thermalPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scrollbar_mode(ui_thermalPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_thermalPanel, LV_DIR_VER);
    lv_obj_set_style_radius(ui_thermalPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_thermalPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_thermalPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_thermalPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_thermalPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_thermalPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_thermalPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_thermalPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempTextPanel = lv_obj_create(ui_thermalPanel);
    lv_obj_set_width(ui_tempTextPanel, 300);
    lv_obj_set_height(ui_tempTextPanel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_tempTextPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tempTextPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_tempTextPanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_tempTextPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_tempTextPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempTextPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempTextPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tempTextPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_tempTextPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tempTextPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tempTextPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tempTextPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_tempTextPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_tempTextPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lowTemp = lv_label_create(ui_tempTextPanel);
    lv_obj_set_width(ui_lowTemp, 100);
    lv_obj_set_height(ui_lowTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lowTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lowTemp, "Low\n--");
    lv_obj_set_style_text_align(ui_lowTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lowTemp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_averageTemp = lv_label_create(ui_tempTextPanel);
    lv_obj_set_width(ui_averageTemp, 100);
    lv_obj_set_height(ui_averageTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_averageTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_averageTemp, "Average\n--");
    lv_obj_set_style_text_align(ui_averageTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_averageTemp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_highTemp = lv_label_create(ui_tempTextPanel);
    lv_obj_set_width(ui_highTemp, 100);
    lv_obj_set_height(ui_highTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_highTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_highTemp, "High\n--");
    lv_obj_set_style_text_align(ui_highTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_highTemp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gridTempPanel = lv_obj_create(ui_thermalPanel);
    lv_obj_set_width(ui_gridTempPanel, 300);
    lv_obj_set_height(ui_gridTempPanel, 300);
    lv_obj_set_align(ui_gridTempPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gridTempPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_gridTempPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_gridTempPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_gridTempPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gridTempPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gridTempPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_gridTempPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_gridTempPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_gridTempPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_gridTempPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_gridTempPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_gridTempPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_gridTempPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_add_event_cb(ui_thermalScreen, ui_event_screen_load, LV_EVENT_SCREEN_LOADED, NULL);
    lv_obj_add_event_cb(ui_thermalScreen, ui_event_screen_unload, LV_EVENT_SCREEN_UNLOADED, (void *)0xAC00);
}
